apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-1-deployment
  labels:
    type: backend
    app: devops-project-1
spec: 
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: devops-project-1
  template:
    metadata:
      name: devops-project-1-pod
      labels:
        type: backend
        app: devops-project-1
    spec:
      containers:
        - name: devops-project-1-container
          image: us.gcr.io/learn-gcp-devops-adarsh/devops-project-1:v1
          ports:
            - containerPort: 80