apiVersion: v1
kind: Service
metadata:
  name: devops-project-1-load-balancer-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    type: backend
    app: devops-project-1
  